#!/bin/sh
# PURPOSE: run only part (i.e. a specific process) of a reference execution
#          (i.e. a captured application)
# USAGE: /path/to/ptu-exec -p [PID]
# LIMITATIONS: assumes this script run from within "ptu" directory

# log file containing processes, files, memory, and resources used by ref exec
logfile=provenance.cde-root.1.log
# ptu executable file (exists if ptu has already been built from source)
built_exec=cde-exec

# no log file (therefore, no app has been captured yet with ptu-audit): abort
if [ ! -f "${logfile}" ]; then
    echo "Error: file ${logfile} not found!"
fi

# no cde-exec file exists (therefore PTU has not been built yet): build it
if [ ! -f "./${built_exec}" ]; then
    cd src
    make
    cp ptu "../${built_exec}"
    cd ..
fi

# run specific process of captured app by calling runpid.py
/usr/bin/env python2 ./runpid.py -f ${logfile} "$@"

