#!/bin/sh
if [ -z "${PTU_HOME+xxx}" ]
then 
  echo PTU_HOME is not set
  exit
fi
rm -f provenance.log

package=./ptu

# make the package
$PTU_HOME/ptu -o $package "$@"
mv $package/cde-exec $package/cde-exec.org 2>/dev/null
cp $PTU_HOME/ptu-exec $package/ 2>/dev/null
cp $PTU_HOME/scripts/runpid.py $package/ 2>/dev/null

python $PTU_HOME/scripts/prov2dot.py 2>/dev/null
mv -f provenance.log gv/ 2>/dev/null

mv gv $package/

cp -r $PTU_HOME $package/src
