#!/bin/sh

logfile=./gv/provenance.log

if [ ! -f $logfile ]
then
    echo "File" $logfile " not found!"
fi

if [ ! -f ./cde-exec ]
then
    cd src
    make
    cp ptu ../cde-exec
    cd ..
fi

/usr/bin/env python2 ./runpid.py -f $logfile "$@"

