#!/bin/sh
# PURPOSE: capture an application's code, data, environment, and provenance
# USAGE: /path/to/ptu-audit /path/to/binary-or-script [binary-or-script args]
# LIMITATIONS: you may NOT run ptu-audit from within the ptu program dir!

# check if user has exported PTU_HOME env var correctly
if [ ! -d "${PTU_HOME}" ]; then
  echo "Error: PTU_HOME environment variable is not set correctly"
  exit
fi

# set the dir to capture the app in, then capture it
package=./ptu
${PTU_HOME}/ptu -o ${package} "$@"

# copy the entire ptu program to the capture dir
cp ${PTU_HOME}/ptu-exec ${package}/
cp ${PTU_HOME}/scripts/runpid.py ${package}/
cp -r ${PTU_HOME} ${package}/src

# generate the process graph and move its output to graph dir "gv"
/usr/bin/env python2 ${PTU_HOME}/scripts/prov2dot.py
mv -f gv ${package}/

# copy ptu log file needed by graph to the graph dir
cp ${package}/provenance.cde-root.1.log ${package}/gv/provenance.log

