#!/bin/sh
if [ -z "${PTU_HOME+xxx}" ]
then 
  echo PTU_HOME is not set
  exit
fi

package=./ptu

# make the package
$PTU_HOME/ptu -o $package "$@"
cp $package/cde-exec $package/cde-exec.org 2>/dev/null
cp $PTU_HOME/ptu-exec $package/ 2>/dev/null
cp $PTU_HOME/scripts/runpid.py $package/ 2>/dev/null

/usr/bin/env python2 $PTU_HOME/scripts/prov2dot.py 2>/dev/null
cp -f ptu/provenance.cde-root.1.log gv/provenance.log 2>/dev/null

mv gv $package/

cp -r $PTU_HOME $package/src

